'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UpdateLibraryProfile

    '''<summary>
    '''ADMT1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ADMT1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Table1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_LibCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_LibCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_Lib_Code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Code As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_Name2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Name2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_Parent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Parent As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_Parent2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Parent2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Add As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_Add2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Add2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_City control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_City As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_City2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_City2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_District control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_District As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_District2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_District2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_State control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_State As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_State2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_State2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_Phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Phone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_Fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Fax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_URL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_URL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_ParentURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_ParentURL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_Incharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Incharge As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_Incharge2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Incharge2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_Timing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Timing As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_SMSuid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_SMSuid As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_SMSpw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_SMSpw As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_SMSsender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_SMSsender As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_SMSip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_SMSip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Lib_Barcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Barcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tr1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''DropDownList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''DropDownList2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr9 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''DDL_Acq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_Acq As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_Lib_Remarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Remarks As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trPw1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPw1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txt_Lib_Intro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Intro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trRpw1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trRpw1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txt_Lib_Intro2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Intro2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tr3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txt_Lib_Objective control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Objective As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tr4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr4 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txt_Lib_Objective2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Objective2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tr5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr5 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txt_Lib_History control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_History As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tr6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr6 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txt_Lib_History2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_History2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tr7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr7 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txt_Lib_Services control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Services As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tr8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr8 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txt_Lib_Services2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lib_Services2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FileUpload13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload13 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''Image22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image22 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''FileUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload1 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''Image23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image23 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''bttn_Update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttn_Update As Global.System.Web.UI.WebControls.Button
End Class
