'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Site

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''HeadContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TrNICImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrNICImage As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Image2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''RKPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RKPass As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''TrUserPhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrUserPhoto As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Image3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image3 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''trLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trLogin As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''trUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trUser As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtUserCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUserCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPassword As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trcaptcha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trcaptcha As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''CAPTCHA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAPTCHA As Global.WebControlCaptcha.CaptchaControl

    '''<summary>
    '''trButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trButton As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''bttn_LogIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttn_LogIn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''trLable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trLable As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Td1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Td1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FGP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FGP As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Tdx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tdx As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TrLogOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrLogOut As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TdLogOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdLogOut As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TR_CREATELOGING control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_CREATELOGING As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''CreateAdmin_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateAdmin_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TRModules control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TRModules As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TRAccordion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TRAccordion As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Accordion1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Accordion1 As Global.AjaxControlToolkit.Accordion

    '''<summary>
    '''DBAdminPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DBAdminPane As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''Adm_Cluster_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Adm_Cluster_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Adm_CreateLibAccount_bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Adm_CreateLibAccount_bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Adm_CreateSUserAccount_bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Adm_CreateSUserAccount_bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Adm_Edit_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Adm_Edit_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Adm_Backup_bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Adm_Backup_bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Adm_Restore_bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Adm_Restore_bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Adm_ViewStats_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Adm_ViewStats_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Database_Log_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Database_Log_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LibAdminPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LibAdminPane As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''Lib_UpdateSUserProfile_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lib_UpdateSUserProfile_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Lib_UpdateLibProfile_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lib_UpdateLibProfile_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Lib_User_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lib_User_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Lib_SysData_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lib_SysData_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Lib_DEFormat_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lib_DEFormat_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Lib_Team_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lib_Team_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Lib_Notice_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lib_Notice_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Lib_Visitors_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lib_Visitors_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Lib_PhotoGallery_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lib_PhotoGallery_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Lib_DataEntryStat_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lib_DataEntryStat_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Lib_Rect_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lib_Rect_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Lib_Feedback_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lib_Feedback_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Lib_Import_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lib_Import_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Lib_Export_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lib_Export_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''MasterPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MasterPane As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''M_UpdateProfile_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M_UpdateProfile_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''M_Committees_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M_Committees_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''M_CommitteeMembers_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M_CommitteeMembers_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''M_Holidays_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M_Holidays_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''M_Labels_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M_Labels_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''M_Pub_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M_Pub_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''M_Vendor_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M_Vendor_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''M_Section_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M_Section_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''M_Subjects_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M_Subjects_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''M_Letter_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M_Letter_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''AcqPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AcqPane As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''Acq_AddTitle_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Acq_AddTitle_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Acq_AddApproval_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Acq_AddApproval_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Acq_Orders_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Acq_Orders_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Acq_Accessioing_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Acq_Accessioing_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CatPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CatPane As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''Cat_Retro_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cat_Retro_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Cat_Status_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cat_Status_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Cat_SV_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cat_SV_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Cat_BarCode_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cat_BarCode_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Cat_Digitals_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cat_Digitals_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CirPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CirPane As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''Cir_Members_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cir_Members_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Cir_Issue_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cir_Issue_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Cir_Transactions_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cir_Transactions_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SerPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SerPane As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''Ser_AddSerial_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ser_AddSerial_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Ser_Approval_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ser_Approval_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Ser_Order_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ser_Order_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Ser_Subscription_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ser_Subscription_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Ser_Schedules_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ser_Schedules_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Ser_ReceiveLoose_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ser_ReceiveLoose_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Ser_Reminders_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ser_Reminders_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Ser_Bound_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ser_Bound_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ArtPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ArtPane As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''Art_Indexing_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Art_Indexing_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''News_Indexing_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents News_Indexing_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BudgPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BudgPane As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''Budg_Budgets_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Budg_Budgets_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Budg_BillProcessing_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Budg_BillProcessing_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Budg_BudgetAnalysys_Bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Budg_BudgetAnalysys_Bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SearchPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchPane As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''Basic_Search_bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Basic_Search_bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Advance_Search_bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Advance_Search_bttn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TR1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Image4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image4 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
